### ISSUE TITLE
Execute parallel tasks for nested tasks in a job spec

### ISSUE THREAD

**Issue by pandemicsyn** [meltano/files-airflow#21]
Given a yaml such as:

```yaml
jobs:
- name: g-to-p-job
  tasks:
  - - tap-gitlab target-postgres
     - tap-github target-postgres
  - dbt-postgres:run
```

Today we create one dag with two connected tasks:

```
#Dag -> task1 -> task2

task1 = meltano run tap-gitlab target-postgres tap-github target-postgres
task2 (depends on task1) = meltano run dbt-postgres:run
```

But it should be "trivial" to parallelize the subtasks rather than flattening them into a single task:

```
#Dag -> task1 (parrallel subtask1, parallel subtask2) -> task2

task1 = (subtask_1, subtask_2)
    subtask_1 = meltano run tap-gitlab target-postgres
    subtask_2 = meltano run tap-github target-postgres
task2 (depends on task1) = meltano run dbt-postgres:run
```

To do so, we'd need just trigger subtask creation at this check: 

https://github.com/meltano/files-airflow/blob/ba72d83f9fc039493e5e80b9c0921ee52cebf6bb/bundle/orchestrate/dags/meltano.py#L145-L147

This parallel execution isn't native to meltano and wouldn't be support yet by `meltano run` natively, but it would at least allow airflow users to leverage parallel subtasks.
